Projem/Projem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projem.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Projem/Projem/Controllers/KarsilastirController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Projem.Models;
using System.Data.SqlClient;

namespace Projem.Controllers
{
    public class KarsilastirController : Controller
    {
        private TelefonEntities db = new TelefonEntities();

        // GET: Karsilastir


        public ActionResult Index()
        {


            var entities = new TelefonEntities();
            var liste = entities.Marka.ToList();
            return View(liste);

        }

    }
}

Projem/Projem/Controllers/UyeGirisiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projem.Controllers
{
    public class UyeGirisiController : Controller
    {
        // GET: UyeGirisi
        public ActionResult Index()
        {
            return View();
        }
    }
}

Projem/Projem/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Projem/Projem/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Projem/Projem/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Ana Sayfa";
}


<p>
    <b>
        Uğur İpek Web Tasarımı Projesi
    </b>
</p>
<img src="~/Content/img/telefon.jpg" />
<p>
    Sitemizin amacı çok basit. Herkes işlemci, ram nedir ne işe yarar gibi bilgilere sahip olmak zorunda değil. Hal böyleyken ihtiyacınıza yönelik telefon seçmekte zorlanabilirsiniz. Biz sizin yerinize piyasadaki tüm telefon marka ve modellerinin özelliklerini araştırıp, hangi telefonun hangi istekleri daha iyi karşıladığını listeledik. Sizin yapmanız gereken tek şey bir telefondan beklentinizi belirtmek ve ihtiyaçlarınız doğrultusunda en uygun telefonu bulmak!
</p>
<br />
<br />
<a href="@Url.Action("Index","Karsilastir")"> <p><input type="submit" value="Karşılaştır" /> </p> </a> 
<br />
<br />
<a href="@Url.Action("Ekle","Create")"> <p><input type="submit" value= "Telefon Ekle" /> </p> </a>
<br />
<br />
<a href="@Url.Action("Index","UyeGirisi")"> <p><input type="submit" value="Üye Girişi" /> </p> </a>